blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('',views.BlogList.as_view(),name="index"),
    path('contact',views.contact,name="contact"),
    path('blog_create',views.blog_create_form),
    path("detail/<int:my_id>",views.detail_view,name='detail'),
    path("delete/<int:my_id>",views.delete_post)
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateField(auto_now_add=True)



class ContactBlog(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField()

    def __str__(self):
        return self.name

comment/models.py
from django.db import models
from blog.models import Blog
from django.contrib.auth.models import User


class Comment(models.Model):
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE,related_name="blog")
    user = models.ForeignKey(User,on_delete=models.CASCADE,related_name="user")
    comment = models.TextField(max_length=500)
    time = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.id},{self.blog.title}"

    def block_comment(self):
        if self.is_active == True:
            self.is_active = False


class ReplyComment(models.Model):
    comment = models.ForeignKey(Comment,on_delete=models.CASCADE,related_name="recomment")
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    re_comment = models.TextField(max_length=500)
    time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.comment.id},{self.comment.blog.title}"

blog/forms.py
from django import forms
from .models import Blog,ContactBlog

class Blogform(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            "title",
            "content"
        ]

#
# class Contactform(forms.Form):
#     name = forms.CharField()
#     email = forms.EmailField()
#     content = forms.Textarea()


class ContactBlogForm(forms.ModelForm):
    class Meta:
        model = ContactBlog
        fields = '__all__'

comment/forms.py
from django import forms
from .models import Comment
from blog.models import Blog
from django.contrib.auth.models import User


class CommentForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea(attrs={
        'placeholder' : 'Write a Comment...'
    }))
    class Meta:
        model = Comment
        fields = [
            'comment',
        ]


# class CommentForm(forms.Form):
#     comment = forms.CharField()
#     name = forms.CharField()

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404,HttpResponseRedirect
from .forms import Blogform,ContactBlogForm
from .models import Blog,ContactBlog
from django.views.generic import ListView
from comment.models import Comment,ReplyComment
from comment.forms import CommentForm
from django.http import JsonResponse

class BlogList(ListView):
    template_name = 'index.html'
    queryset = Blog.objects.all()


# def index(request):
#     queryset = Blog.objects.all()
#     dic = {
#         'posts' : queryset
#     }
#     return render(request,'index.html',dic)


# def contact(request):
#     if request.method == "POST":
#         form = Contactform(request.POST)
#         if form.is_valid():
#             name = form.cleaned_data.get("name")
#             email = form.cleaned_data.get("email")
#         print(name,email)
#         print(form.cleaned_data)
#     else:
#         form = Contactform()
#
#     dic = {
#         "form" : form
#         }
#
#     return render(request,"contact.html",dic)

def contact(request):
    form = ContactBlogForm(request.POST or None)
    data = {}
    if request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        content = request.POST.get('content')
        ContactBlog.objects.create(name=name, email = email, content = content)
        data['name']=name
        data['email']=email
        data['content']=content
        return JsonResponse(data, safe=False)

    dic = {
    'form' : form
    }
    return render(request, "contact.html",dic)



def blog_create_form(request):
    form = Blogform(request.POST)
    if form.is_valid():
        form.save()
        form = Blogform()
    dic = {
        "form" : form
    }
    return render(request,'blog_create.html',dic)


def detail_view(request,my_id):
    # obj = Blog.objects.get(pk=my_id)
    obj = get_object_or_404(Blog,pk=my_id)
    user = request.user
    # get comment from Comment with pk
    comments = Comment.objects.filter(blog_id=my_id)
    is_active = True
    # creat_comment part
    # initial_data = {
    #     'blog':obj,
    #     'user':user
    # }

    form = CommentForm(request.POST)
    if request.method == "POST" and form.is_valid():
        instance = form.save(commit=False)
        instance.blog = obj
        instance.user = user
        instance.save()
    form = CommentForm()
    dic = {
        "object" : obj,
        "comments":comments,
        "is_active":is_active,
        "form" : form
    }
    print(form.as_p)
    return render(request,"detail.html",dic)



def delete_post(request,my_id):
    obj = get_object_or_404(Blog, pk=my_id)
    if request.method == "POST":
        obj.delete()
        return HttpResponseRedirect("/")

    return render(request,"delete_post.html")

comment/views.py
from django.shortcuts import render

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Rabin Web</title>
    <!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>
  <body>
<div class="container">
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'blog:index' %}">Rabin Web</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:contact' %}">Contact</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>

    </ul>
  </div>
  <div class="nav-btn">
    {% if user.is_authenticated %}
    <span>Hi {{user.username}}</span>
    {% else %}
    <button type="button" class="btn btn-success">Login</button>
    {% endif %}
  </div>
</nav>
</header>


<div class="content-box">

<div class="box1">

{% block content %}

<div class="content">
  <div class="c-title">
    <h6>Django django django</h6>
  </div>
  <div class="c-content">
    <p>Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.

</p>
  </div>

  <div class="c-pup">
    <span>pup date : 15.09.2020</span>
  </div>
</div>


{% endblock %}






</div>

<div class="box2">
  <div class="arch">
    <div class="arch-title">
      <span>Title</span>
    </div>
<div class="arch-content">
  <ul>
    {% regroup all_posts by pub_date as objs %}

        {% for group in objs %}

          <!-- <a href="#"><li>{{ group.grouper }}</li></a> -->

          {% for item in group.list %}
            <a href="{% url 'blog:detail' my_id=item.id %}"><li>{{ item.title }}</li></a>

      {% endfor %}

  {% endfor %}


  </ul>
</div>
  </div>
</div>


</div>



</div>
  </body>
</html>

templates/blog_create.html
{% extends 'base.html' %}


{% block content %}

<div class="content">
  <div class="c-title">
    <h6>Form</h6>
  </div>
  <div class="c-content">


<p>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="send">
</form>


</p>

  </div>


</div>



{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% block content %}

<div id="alert">
</div>
<form method="POST" id="myForm">
  {{ form.as_p }}{% csrf_token %}
  <button type="submit" name="send">send</button>
</form>


<script type="text/javascript">
  const form = document.getElementById('myForm')
  const box = document.getElementById('alert')
  const name = document.getElementById('id_name')
  const email = document.getElementById('id_email')
  const content = document.getElementById('id_content')
  const csrf = document.getElementsByName('csrfmiddlewaretoken')
  const url = "{% url 'blog:contact' %}"
  const handelAlert = (type, text) =>{
    box.innerHTML += `<div class="alert alert-${type}" role="alert">${text}</div>`
  }

  form.addEventListener('submit',(e)=>{
    e.preventDefault()
    console.log("submitted")
    $.ajax({
      type: 'POST',
      url : url,
      data : {
        'csrfmiddlewaretoken' : csrf[0].value,
        'name' : name.value,
        'email' : email.value,
        'content' : content.value,
      },
      success: function(response){
        const sText = `Successfuly saved ${response.name}`
        handelAlert('success',sText)
        name.value = ""
        email.value = ""
        content.value = ""
      },
      error: function(error){
        handelAlert('success', 'Ups ... somthing went wrong')
      }
    })
  })
</script>
{% endblock %}

templates/create_comment.html
<form method="POST">{% csrf_token %}
  {{ form.as_p }}
<input type="submit" value="send">
</form>

templates/delete_post.html
{% extends 'base.html' %}


{% block content %}

<div class="content">
  <div class="c-title">
    <h6>Delete</h6>
  </div>
  <div class="c-content">


<p>

<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Delete">
</form>


</p>

  </div>


</div>



{% endblock %}

templates/detail.html
{% extends 'base.html' %}


{% block content %}

<div class="content">
  <div class="c-title">
    <h6> <a href="{% url 'blog:detail' my_id=object.id %}">{{ object.title }}</a> </h6>
  </div>
  <div class="c-content">
<p>{{ object.content }}</p>
  </div>

  <div class="c-pup">
    <span>pup date : {{ object.pub_date }}</span>
  </div>
</div>


<form method="POST">
  {% csrf_token %}
  {{ form.as_p }}
<input type="submit" value="send">
</form>


<br>
{% if comments %}

    {% for comment in comments %}

      <ul>
        <li>{{comment.pk}},{{ comment.comment }}
            <ul>
              <li class="comment-detail">@ {{comment.user.username}} | {{comment.time }}</li>
              <hr>
              {# {% if re_comments %} #}
                {% for reply in comment.recomment.all %}
                  <li>{{ reply.re_comment }}</li>
                  <li class="comment-detail">@ {{reply.user.username}} | {{reply.time }}</li>
                {% endfor %}
              {# {% endif %} #}
            </ul>
        </li>
      </ul>
    {% endfor %}

{% else %}

    <ul>
      <li>No Comments for this post !</li>
    </ul>



{% endif %}



{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block content %}
  {% for post in object_list %}
  <div class="content">
    <div class="c-title">
      <h6> <a href="{% url 'blog:detail' my_id=post.id %}">{{ post.title }}</a> </h6>
    </div>
    <div class="c-content">
  <p>{{ post.content }}</p>
    </div>

    <div class="c-pup">
      <span>pup date : {{ post.pub_date }}</span>
    </div>
  </div>
  {% endfor %}
{% endblock %}